version: '2'

services:
    web:
        image: nginx:latest
        container_name: vedomoney-nginx
        ports:
            - "8085:80"
        volumes:
            - ./code:/code
            - ./logs:/var/log/nginx/
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build: 
          context: ./
          dockerfile: laravel.docker
        container_name: vedomoney-laravel
        working_dir: /code
        volumes:
            - ./code:/code
        environment:
            - APP_LOG_LEVEL=debug
        links:
            - vedomoney_db
    vedomoney_db:
        image: mariadb
        restart: always
        ports:
            - 3310:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: vedomoney
            MYSQL_USER: vedomoney
            MYSQL_PASSWORD: 123456